language: go
arch:
- amd64
- ppc64le
go:
- 1.19.x
- 1.18.x

git:
  depth: false

install:
- go get -t ./...
- go install github.com/mattn/goveralls@latest
- go install honnef.co/go/tools/cmd/staticcheck@latest
- go install github.com/client9/misspell/cmd/misspell@latest

before_script:
- $(exit $(go fmt ./... | wc -l))
- go vet ./...
- misspell -error -locale US .
- misspell -error -locale US ./nk
- staticcheck ./...

script:
- go test -v -vet=off --race --failfast
- go test -v -covermode=count -coverprofile=coverage.out
- $HOME/gopath/bin/goveralls -coverprofile coverage.out -service travis-ci

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL http://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
